s1=input("Enter the elements in set1:\n")
s1=set(map(int,s1.split(',')))
s2=input("Enter the elements in set2:\n")
s2=set(map(int,s2.split(',')))
s1length=len(s1)
s2length=len(s2)
print("The length of elements in two sets are equal:",bool(s1length==s2length))
s1sum=sum(s1)
s2sum = sum(s2)
print("The sums are equal",bool(s1sum=s2sum))
print("The set has common elements",bool(len(s1&s2)))
